spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/User
    username: TricklingEnigma
    password: root
  data:
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
server:
  tomcat:
    relaxed-query-chars: |
  port: 8060